(def (make-segment v1 v2)
  (cons v1 v2)
  )
(def (get-start s1)
  (car s1)
  )
(def (get-end s1)
  (cdr s1)
  )
(def (make-vect x y)
  (cons x y)
  )
(def (get-x v)
  (car v)
  )
(def (get-y v)
  (cdr v)
  )
(def (op-both method v1 v2)
  (cons (method (car v1) (car v2)) (method (cdr v1) (cdr v2)))
  )
(def (add-vect v1 v2)
  (op-both + v1 v2)
  )
(def (sub-vect v1 v2)
  (op-both + v1 v2)
  )
(def (scale-vect s v)
  (cons (* s (car v)) (* s (cdr v)))
  )
(def (draw v-start v-end)
  ;doesn't actually exist, just test
  (cons v-start v-end)
  )
(def (print-frame s1 s2)
  (begin (draw (get_start s1) (get_end s1))
         (draw (get_start s2) (get_end s2))
         (draw ((get_start s1)) (get_end s1))
         )
  )