;line segment creation

(define (make-point x y)
  (cons x y)
  )
(define (x-val point)
  (car point)
  )
(define (y-val point)
  (cdr point)
  )
(define (start-segment segment)
  (car segment)
  )
(define (end-segment segment)
  (cdr segment)
  )
(define (print-point point)
  (display "(")
  (display (x-val point))
  (display " ,")
  (display (y-val point))
  (display ")")
  )
(define (print-segment segment)
  (newline)
  (display "(")
  (print-point (car segment))
  (display " --> ")
  (print-point (cdr segment))
  (display ")")
  (newline)
  )

(define (make-segment point1 point2)
  (cons point1 point2)
  )

(define (midpoint segment)
  (make-point (/ (+ (x-val (start-segment segment)) (x-val (end-segment segment)) ) 2.0)
              (/ (+ (y-val (start-segment segment)) (y-val (end-segment segment))) 2.0)
              )
  )

(define seg1 (make-segment (make-point 1 2) (make-point 3 4)))

(print-segment seg1)
(midpoint seg1)


