(define (interval low high)
  (cons low high)
  )
(define (low i1)
  (car i1)
  )
(define (high i2)
  (cdr i2)
  )
(define (width-interval i1)
  (/ (- (high i1) (low i1)) 2)
  )
(define (add-interval i1 i2)
  (cons (+ (low i1) (low i2)) (+ (high i1) (high i2)))
  )
(define (sub-interval i1 i2)
  (cons (- (low i1) (low i2)) (- (high i1) (high i2)))
  )
(define (mul-interval i1 i2)
  (cons (* (low i1) (low i2)) (* (high i1) (high i2)))
  )
(define (div-interval i1 i2)
  (cons (/ (low i1) (low i2)) (/ (high i1) (high i2)))
  )

(define i1 (interval -1 -5))
(define i2 (interval -8 -9))


(add-interval i1 i2)
(sub-interval i1 i2)
(mul-interval i1 i2)