; 561 1105 1729 2465 2821 6601
(define (iter n a)
  (if (not (= a n)) (fermat n a))
  )
(define (exp-1 x p)
  (cond ((= p 0) 1)
        ((= p 1) x)
        (else (* x (exp-1 x (- p 1))))
        )
  )
(define (is-prime n a)
  (display #t)
  (newline)
  (iter n (+ a 1))
  )
(define (fermat n a)
    (if (= (remainder (exp-1 a n) n) (remainder a n)) (is-prime n a) #f)
    )

(define (carmichael n)
  (iter n 1)
  )
(carmichael 6601)