(define (make-rect l1 l2 point)
  (cons point (cons l1 l2))
  )
(define (x point)
  (car point)
  )
(define (y point)
  (cdr point)
  )
(define (base-point r1)
  (car r1)
  )
(define (side-1 r1)
  (cdr (car r1))
  )
(define (side-2 r1)
  (cdr (cdr r1))
  )

(define (print-rect r1)
  (let ((l1 (side-1 r1))
       (l2 (side-2 r2))
       (point (base-point r1)))

    (newline)
    (display point)
    (newline)
    (display (cons ()))
    )
  )
