(define (pyramid height tag)
  (iter-height 0 1 height (+ 1 (* 2 height)) tag)
  )

(define (iter-height current num height width tag)
  (if (= current height) "done" (print-line current 0 num (- width num)) tag height width)
  )

(define (print-line current current2 tag_num space_num tag height width)
  (define (print-final )
    (if (= current height ))
    )
  (define (print-space )
    (display " ")
    )
  (define (print-tag )
    (display tag)
    )
  (if (< current2 space_num) (print-space )
      (if (>= current2 (+ space_num tag_num)) (print-space ) (print-tag tag ))
      )
  )
